In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

import matplotlib.pyplot as plt
import re

In [3]:
from zipfile import ZipFile
with ZipFile('20k_dataset.zip', 'r') as zf:
    zf.extractall('./')

In [51]:
news_train_df = pd.read_csv('./train.csv')
news_train_df.head(20)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
6    6  Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
8    8  Excerpts From a Draft Script for Donald Trump’...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
12  12  Russian Researchers Discover Secret Nazi Milit...   
13  13  US Officials See No Link Between Trump and Russia   
14  14  Re: Yes, There Are Paid Government Trolls On S...   
15  15  In Major League Soccer, Argentines Find a Home...   
16  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
17  17  Anonymous Donor Pays $2.5 Million To Release E...   
18  18                          FBI Closes In On Hillary!   
19  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   

                              author  \
0                      Darrell Lucus   
1                    Daniel J. Flynn   
2                 Consortiumnews.com   
3                    Jessica Purkiss   
4                     Howard Portnoy   
5                    Daniel Nussbaum   
6                                NaN   
7                    Alissa J. Rubin   
8                                NaN   
9       Megan Twohey and Scott Shane   
10                       Aaron Klein   
11                   Chris Tomlinson   
12                     Amando Flavio   
13                        Jason Ditz   
14                      AnotherAnnie   
15                     Jack Williams   
16  Michael Corkery and Stacy Cowley   
17                          Starkman   
18                           The Doc   
19                         Jeff Poor   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
6   Ever wonder how Britain’s most iconic pop pian...      1  
7   PARIS  —   France chose an idealistic, traditi...      0  
8   Donald J. Trump is scheduled to make a highly ...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0  
12  The mystery surrounding The Third Reich and Na...      1  
13  Clinton Campaign Demands FBI Affirm Trump's Ru...      1  
14  Yes, There Are Paid Government Trolls On Socia...      1  
15  Guillermo Barros Schelotto was not the first A...      0  
16  The scandal engulfing Wells Fargo toppled its ...      0  
17  A Caddo Nation tribal leader has just been fre...      1  
18  FBI Closes In On Hillary! Posted on Home » Hea...      1  
19  Wednesday after   Donald Trump’s press confere...      0

In [94]:
news_test_df = pd.read_csv('./test.csv')
news_test_df

id                                              title  \
0     20800  Specter of Trump Loosens Tongues, if Not Purse...   
1     20801  Russian warships ready to strike terrorists ne...   
2     20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3     20803  Tim Tebow Will Attempt Another Comeback, This ...   
4     20804                    Keiser Report: Meme Wars (E995)   
...     ...                                                ...   
5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
5197  25997  California Today: What, Exactly, Is in Your Su...   
5198  25998  300 US Marines To Be Deployed To Russian Borde...   
5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  \
0            David Streitfeld   
1                         NaN   
2               Common Dreams   
3               Daniel Victor   
4     Truth Broadcast Network   
...                       ...   
5195               Jody Rosen   
5196      Sheryl Gay Stolberg   
5197             Mike McPhate   
5198                      NaN   
5199              Teddy Wayne   

                                                   text  
0     PALO ALTO, Calif.  —   After years of scorning...  
1     Russian warships ready to strike terrorists ne...  
2     Videos #NoDAPL: Native American Leaders Vow to...  
3     If at first you don’t succeed, try a different...  
4     42 mins ago 1 Views 0 Comments 0 Likes 'For th...  
...                                                 ...  
5195  Of all the dysfunctions that plague the world’...  
5196  WASHINGTON  —   Gov. John Kasich of Ohio on Tu...  
5197  Good morning. (Want to get California Today by...  
5198  « Previous - Next » 300 US Marines To Be Deplo...  
5199  Perhaps you’ve seen the new TV series whose pi...  

[5200 rows x 4 columns]

In [77]:
bool_series_t = pd.notnull(news_train_df['title'])
news_train_df[bool_series_t]

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20198  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  20797  Macy’s Is Said to Receive Takeover Approach by...   
20201  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20202  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 5 columns]

In [79]:
news_train_df = news_train_df[bool_series_t].reset_index(drop =True)
news_train_df= news_train_df.reset_index(drop=True)


id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20198  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  20797  Macy’s Is Said to Receive Takeover Approach by...   
20201  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20202  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 5 columns]

In [80]:
news_train_df.drop(columns= ['id'])
news_train_df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20198  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  20797  Macy’s Is Said to Receive Takeover Approach by...   
20201  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20202  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 5 columns]

In [81]:
bool_series_text = pd.notnull(news_train_df['text'])
news_train_df = news_train_df[bool_series_text]

In [82]:
news_train_df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20198  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  20797  Macy’s Is Said to Receive Takeover Approach by...   
20201  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20202  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 5 columns]

In [83]:
bool_series_text = pd.notnull(news_train_df['text'])
news_train_df = news_train_df[bool_series_text]
news_train_df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20198  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  20797  Macy’s Is Said to Receive Takeover Approach by...   
20201  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20202  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 5 columns]

In [84]:
news_train_df.columns

Index(['id', 'title', 'author', 'text', 'label'], dtype='object')

In [89]:
news_train_df=news_train_df.drop(columns = ['id'])

In [90]:
news_train_df

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
20198  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  Macy’s Is Said to Receive Takeover Approach by...   
20201  NATO, Russia To Hold Parallel Exercises In Bal...   
20202                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  Rapper T. I. unloaded on black celebrities who...      0  
20199  When the Green Bay Packers lost to the Washing...      0  
20200  The Macy’s of today grew from the union of sev...      0  
20201  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20202    David Swanson is an author, activist, journa...      1  

[20203 rows x 4 columns]

In [86]:
from wordcloud import STOPWORDS
STOPWORDS.add("rt")
STOPWORDS.add("s")
STOPWORDS.add("u")
STOPWORDS.add("amp")
STOPWORDS.add("th")
STOPWORDS.add("will")
STOPWORDS.add("t")
STOPWORDS.add("m")

In [87]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('universal_tagset')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('sentiwordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package universal_tagset to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package sentiwordnet to
[nltk_data]     C:\Users\Mahima\AppData\Roaming\nltk_data...
[nltk_data]   Package sentiword

True

In [91]:
import re
for i in range(len(news_train_df)):
    d = news_train_df.loc[i]["text"]
    d=re.sub(r'http\S+', '', d) #remove links
    d=re.sub("[^a-zA-Z]", " ", d) #remove all characters except letters
    d=d.lower() #convert all words to lowercase
    d=nltk.word_tokenize(d) #split sentences into word
    d=[word for word in d if not word in STOPWORDS] #remove the stopwords
    lemma=nltk.WordNetLemmatizer() 
    d=[lemma.lemmatize(word) for word in d] #identify the correct form of the word in the dictionary
    d=" ".join(d)
    
    news_train_df.at[i,"text"]=d

In [106]:
news_train_df

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
20198  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  Macy’s Is Said to Receive Takeover Approach by...   
20201  NATO, Russia To Hold Parallel Exercises In Bal...   
20202                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
0      house dem aide didn even see comey letter jaso...      1  
1      feeling life circle roundabout rather head str...      0  
2      truth might fired october tension intelligence...      1  
3      video civilian killed single airstrike identif...      1  
4      print iranian woman sentenced six year prison ...      1  
...                                                  ...    ...  
20198  rapper unloaded black celebrity met donald tru...      0  
20199  green bay packer lost washington redskin week ...      0  
20200  macy today grew union several great name ameri...      0  
20201  nato russia hold parallel exercise balkan pres...      1  
20202  david swanson author activist journalist radio...      1  

[20203 rows x 4 columns]

In [111]:
news_training_df  = news_train_df.iloc[:15000,:]
news_testing_df = news_train_df.iloc[15001:,:]
news_testing_df

title  \
15001  Monsieur Malbrough est Mort | New Eastern Outlook   
15002  C.I.A. Chief Warns Donald Trump Against Tearin...   
15003        Seattle Doling Legal Aid for Illegal Aliens   
15004  This Honest Trailer for Sherlock is hilarious ...   
15005  Hillary Clinton Jumps the Shark with ‘Trump’s ...   
...                                                  ...   
20198  Rapper T.I.: Trump a ’Poster Child For White S...   
20199  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20200  Macy’s Is Said to Receive Takeover Approach by...   
20201  NATO, Russia To Hold Parallel Exercises In Bal...   
20202                          What Keeps the F-35 Alive   

                                          author  \
15001                                     Author   
15002                               Dan Bilefsky   
15003                                John Binder   
15004                                         OK   
15005                                        NaN   
...                                          ...   
20198                              Jerome Hudson   
20199                           Benjamin Hoffman   
20200  Michael J. de la Merced and Rachel Abrams   
20201                                Alex Ansary   
20202                              David Swanson   

                                                    text  label  
15001  region europe recently published article title...      1  
15002  london director c issued stark warning donald ...      0  
15003  taxpayer seattle soon paying illegal alien rec...      0  
15004  next prev swipe left right honest trailer sher...      1  
15005  st century wire say yesterday wikileaks editor...      1  
...                                                  ...    ...  
20198  rapper unloaded black celebrity met donald tru...      0  
20199  green bay packer lost washington redskin week ...      0  
20200  macy today grew union several great name ameri...      0  
20201  nato russia hold parallel exercise balkan pres...      1  
20202  david swanson author activist journalist radio...      1  

[5202 rows x 4 columns]

In [100]:
from nltk.stem.lancaster import LancasterStemmer
st = LancasterStemmer()

def token(text):
    txt = nltk.word_tokenize(text.lower())
    return [st.stem(word) for word in txt]

In [101]:
#cv = CountVectorizer(lowercase=True, 
#                     tokenizer=token, stop_words=STOPWORDS,
#                     analyzer=u'word', min_df=4)

tv = TfidfVectorizer(stop_words = STOPWORDS,
                     lowercase=True, binary = True)

In [112]:
vec_train = tv.fit_transform(news_training_df['text'])
vec_test = tv.transform(news_testing_df['text'])

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import  accuracy_score, confusion_matrix, classification_report


rfc = RandomForestClassifier(n_estimators=100, n_jobs=-1)
rfc.fit(X = vec_train, y = news_training_df['label'])

y_pred_rfc=rfc.predict(vec_test)
#accuracy_score(y_pred_rfc, test_target)


In [114]:
rfc_report=classification_report(news_testing_df['label'],y_pred_rfc)
print(rfc_report)

              precision    recall  f1-score   support

           0       0.87      0.94      0.91      2657
           1       0.93      0.86      0.89      2545

    accuracy                           0.90      5202
   macro avg       0.90      0.90      0.90      5202
weighted avg       0.90      0.90      0.90      5202



In [118]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=25000, n_features=4, n_informative=3, n_redundant=0, random_state=1)
model = RandomForestClassifier()
model.fit(X, y)
importance = model.feature_importances_
# summarize feature importance
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))
print(X ,y)

Feature: 0, Score: 0.12597
Feature: 1, Score: 0.02453
Feature: 2, Score: 0.72096
Feature: 3, Score: 0.12853
[[-0.08475204 -2.11716863  0.85175395 -1.03890271]
 [-2.71598525 -1.09189784 -1.95020879  0.46621376]
 [ 0.97293604 -0.34125398 -0.0778616   2.36914395]
 ...
 [ 2.31358491  0.39831978  1.76317605  1.27989382]
 [ 0.80842384 -0.39330673  0.4746392   1.37447403]
 [-1.65783831 -0.27461375 -2.19101279  3.08144064]] [0 1 1 ... 0 0 1]
